// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// get_motif_ix
arma::sp_mat get_motif_ix(List mats, const std::vector<std::string> x, const std::vector<double> nuc_freqs, const double p, const size_t w);
RcppExport SEXP MOODSR_get_motif_ix(SEXP matsSEXP, SEXP xSEXP, SEXP nuc_freqsSEXP, SEXP pSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type mats(matsSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type nuc_freqs(nuc_freqsSEXP);
    Rcpp::traits::input_parameter< const double >::type p(pSEXP);
    Rcpp::traits::input_parameter< const size_t >::type w(wSEXP);
    __result = Rcpp::wrap(get_motif_ix(mats, x, nuc_freqs, p, w));
    return __result;
END_RCPP
}
// get_max_motif_score
arma::sp_mat get_max_motif_score(List& mats, const std::vector<std::string> x, const std::vector<double> nuc_freqs, const double p, const size_t w);
RcppExport SEXP MOODSR_get_max_motif_score(SEXP matsSEXP, SEXP xSEXP, SEXP nuc_freqsSEXP, SEXP pSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List& >::type mats(matsSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type nuc_freqs(nuc_freqsSEXP);
    Rcpp::traits::input_parameter< const double >::type p(pSEXP);
    Rcpp::traits::input_parameter< const size_t >::type w(wSEXP);
    __result = Rcpp::wrap(get_max_motif_score(mats, x, nuc_freqs, p, w));
    return __result;
END_RCPP
}
