# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_thresholds <- function(mats, nuc_freqs, p) {
    .Call('MOODSR_get_thresholds', PACKAGE = 'MOODSR', mats, nuc_freqs, p)
}

get_motif_ix <- function(mats, x, nuc_freqs, p, w) {
    .Call('MOODSR_get_motif_ix', PACKAGE = 'MOODSR', mats, x, nuc_freqs, p, w)
}

get_max_motif_score <- function(mats, x, nuc_freqs, p, w) {
    .Call('MOODSR_get_max_motif_score', PACKAGE = 'MOODSR', mats, x, nuc_freqs, p, w)
}

get_motif_positions <- function(mats, x, nuc_freqs, p, w) {
    .Call('MOODSR_get_motif_positions', PACKAGE = 'MOODSR', mats, x, nuc_freqs, p, w)
}

